# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-05-29 07:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bills',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('billcoast', models.IntegerField(default=1, null=True)),
                ('billdate', models.CharField(max_length=45, null=True)),
                ('billstat', models.CharField(default='Unpaid', max_length=45)),
                ('instalment', models.IntegerField(null=True)),
                ('userbill', models.CharField(max_length=45, null=True)),
                ('paiddate', models.CharField(max_length=45, null=True)),
                ('userpaid', models.CharField(max_length=45, null=True)),
                ('startdate', models.CharField(max_length=45, null=True)),
                ('enddate', models.CharField(max_length=45, null=True)),
                ('billc', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('create', models.DateTimeField(auto_now_add=True, null=True)),
                ('Arabicfirstname', models.CharField(max_length=45)),
                ('Arabicmiddlename', models.CharField(max_length=45)),
                ('Arabicthirdname', models.CharField(max_length=45)),
                ('Arabiclastname', models.CharField(max_length=45)),
                ('Englishfirstname', models.CharField(max_length=45, null=True)),
                ('Englishmiddlename', models.CharField(max_length=45, null=True)),
                ('Englishthirdname', models.CharField(max_length=45, null=True)),
                ('Englishlastname', models.CharField(max_length=45, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('service', models.EmailField(max_length=254, null=True)),
                ('bundle', models.EmailField(max_length=254, null=True)),
                ('speed', models.EmailField(max_length=254, null=True)),
                ('period', models.EmailField(max_length=254, null=True)),
                ('SecondaryEmail1', models.EmailField(max_length=254, null=True)),
                ('SecondaryEmail2', models.EmailField(max_length=254, null=True)),
                ('mobile', models.CharField(max_length=45)),
                ('SecondaryMobile1', models.CharField(max_length=45, null=True)),
                ('SecondaryMobile2', models.CharField(max_length=45, null=True)),
                ('Fax', models.CharField(max_length=45, null=True)),
                ('Nationality', models.CharField(max_length=45)),
                ('city', models.CharField(max_length=45)),
                ('username', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('identity', models.IntegerField(default=1)),
                ('address', models.CharField(max_length=45)),
                ('status', models.CharField(default='Activation', max_length=45)),
                ('update', models.CharField(max_length=45, null=True)),
                ('emergency', models.CharField(max_length=45, null=True)),
                ('emergencycount', models.IntegerField(default=0, null=True)),
                ('usercustomer', models.CharField(max_length=45, null=True)),
                ('street', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='edit_note',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('editname', models.CharField(max_length=45, null=True)),
                ('editdate', models.CharField(max_length=45, null=True)),
                ('useredit', models.CharField(max_length=45, null=True)),
                ('editreport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.customer')),
            ],
        ),
        migrations.CreateModel(
            name='emploeey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.IntegerField(default=100)),
                ('efname', models.CharField(max_length=45)),
                ('elname', models.CharField(max_length=45)),
                ('esalary', models.IntegerField(default=170)),
                ('epassword', models.CharField(max_length=45)),
                ('edateofharing', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='note',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notename', models.CharField(max_length=45, null=True)),
                ('notedate', models.CharField(max_length=45, null=True)),
                ('new_status', models.CharField(max_length=45, null=True)),
                ('usernote', models.CharField(max_length=45, null=True)),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.customer')),
            ],
        ),
        migrations.CreateModel(
            name='replay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('replaybody', models.CharField(max_length=45, null=True)),
                ('replaydate', models.CharField(max_length=45, null=True)),
                ('userreplay', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tickname', models.CharField(max_length=45, null=True)),
                ('tickdate', models.CharField(max_length=45, null=True)),
                ('tickstatus', models.CharField(default='open', max_length=45)),
                ('close', models.CharField(max_length=45, null=True)),
                ('closedate', models.CharField(max_length=45, null=True)),
                ('useradd', models.CharField(max_length=45, null=True)),
                ('userclose', models.CharField(max_length=45, null=True)),
                ('ticktype', models.CharField(max_length=45, null=True)),
                ('ticksub', models.CharField(max_length=45, null=True)),
                ('tickreport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.customer')),
            ],
        ),
        migrations.CreateModel(
            name='vas',
            fields=[
                ('sname', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('scoast', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='vas1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sname1', models.CharField(max_length=45)),
                ('vasstat', models.CharField(max_length=45, null=True)),
                ('vstartdate', models.CharField(max_length=45, null=True)),
                ('venddate', models.CharField(max_length=45, null=True)),
                ('uservas', models.CharField(max_length=45, null=True)),
                ('billid', models.CharField(max_length=45, null=True)),
                ('vasreport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.customer')),
            ],
        ),
        migrations.AddField(
            model_name='replay',
            name='replayreport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.ticket'),
        ),
        migrations.AddField(
            model_name='bills',
            name='cusbill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.customer'),
        ),
    ]
