# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-06-01 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20200529_0717'),
    ]

    operations = [
        migrations.CreateModel(
            name='instalment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('instalment', models.IntegerField(null=True)),
                ('paiddate', models.CharField(max_length=45, null=True)),
                ('userpaid', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='bills',
            name='instalment',
        ),
        migrations.RemoveField(
            model_name='bills',
            name='paiddate',
        ),
        migrations.RemoveField(
            model_name='bills',
            name='userpaid',
        ),
    ]
