# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-06-01 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20200601_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='instalment',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
