# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-06-01 04:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_bills_instalment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instalment',
            old_name='instalment',
            new_name='payment',
        ),
    ]
