# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-06-01 04:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_bills_userpaid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='instalment',
            new_name='instalment10',
        ),
    ]
