# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-06-01 04:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_auto_20200601_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalment10',
            name='cuspaid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.customer'),
        ),
    ]
