# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-06-02 23:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_auto_20200601_0503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Arabicfirstname',
            new_name='Arabicname',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Englishfirstname',
            new_name='Englishname',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='Arabiclastname',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='Arabicmiddlename',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='Arabicthirdname',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='Englishlastname',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='Englishmiddlename',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='Englishthirdname',
        ),
    ]
