# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-07-26 02:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_auto_20200602_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emploeey',
            name='edateofharing',
        ),
        migrations.RemoveField(
            model_name='emploeey',
            name='elname',
        ),
        migrations.RemoveField(
            model_name='emploeey',
            name='epassword',
        ),
        migrations.RemoveField(
            model_name='emploeey',
            name='esalary',
        ),
    ]
