# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-07-26 02:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_auto_20200726_0213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='efname',
            new_name='ename',
        ),
    ]
