# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-07-26 02:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_auto_20200726_0232'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='employee',
            new_name='employee1',
        ),
    ]
