# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-07-27 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_employee1_vacation'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee1',
            name='endtime',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee1',
            name='worktime',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
    ]
