# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-07-27 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_auto_20200727_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee1',
            name='endtime',
            field=models.TimeField(default='4:00 PM'),
        ),
        migrations.AlterField(
            model_name='employee1',
            name='worktime',
            field=models.TimeField(default='8:00 AM'),
        ),
    ]
