# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-07-27 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_auto_20200727_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee1',
            name='endtime',
            field=models.TimeField(default='16:00'),
        ),
        migrations.AlterField(
            model_name='employee1',
            name='worktime',
            field=models.TimeField(default='8:00'),
        ),
    ]
