# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-07-29 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_auto_20200727_0632'),
    ]

    operations = [
        migrations.CreateModel(
            name='vacation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vdate', models.CharField(max_length=45)),
            ],
        ),
    ]
