# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-07-29 01:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_vacation'),
    ]

    operations = [
        migrations.CreateModel(
            name='vacations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vdate', models.CharField(max_length=45)),
                ('evdate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.employee1')),
            ],
        ),
        migrations.DeleteModel(
            name='vacation',
        ),
    ]
