# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-07-29 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0025_auto_20200729_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacations',
            name='id1',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
    ]
