# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-07-29 03:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_vacations_id1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacations',
            name='id1',
        ),
    ]
