# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-07-29 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0027_remove_vacations_id1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee1',
            name='worktime',
            field=models.DateField(default='8:00'),
        ),
    ]
