# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-07-29 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0029_auto_20200729_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacations',
            name='vdate',
            field=models.DateField(max_length=45),
        ),
    ]
