# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-07-30 01:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0032_vacations_weekend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacations',
            name='weekend',
        ),
    ]
