# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-08-15 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0033_remove_vacations_weekend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='create',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
