# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-08-15 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0034_auto_20200815_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='new_Email',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
