# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-08-15 04:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0035_note_new_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='general_note',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('generalname', models.CharField(max_length=45, null=True)),
                ('generaldate', models.CharField(max_length=45, null=True)),
                ('usergeneral', models.CharField(max_length=45, null=True)),
                ('generalreport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.customer')),
            ],
        ),
        migrations.RemoveField(
            model_name='note',
            name='new_Email',
        ),
    ]
