# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-18 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0038_auto_20200817_0531'),
    ]

    operations = [
        migrations.CreateModel(
            name='USCitizen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('can_drive', 'Can drive'), ('can_vote', 'Can vote in elections'), ('can_drink', 'Can drink alcohol')),
            },
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': (('can_email', 'Can Send Email'),)},
        ),
    ]
