# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-18 06:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0039_auto_20200818_0645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
    ]
