# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-18 07:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0041_auto_20200818_0655'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': (('can_show_customer', 'Can show customer'),)},
        ),
    ]
