# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-22 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0043_auto_20200820_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='replay',
            name='id1',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
