# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-30 02:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0046_customer_payment_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='promotions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthnum', models.CharField(max_length=45, null=True)),
                ('userprom', models.CharField(max_length=45, null=True)),
                ('cusprom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.customer')),
            ],
        ),
        migrations.AddField(
            model_name='bills',
            name='prom',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
