# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-30 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0047_auto_20200830_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotions',
            name='prodate',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
