# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-30 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0049_promotions_billid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='enddate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='bills',
            name='startdate',
            field=models.DateField(null=True),
        ),
    ]
