# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-04 03:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='custumer',
            fields=[
                ('username', models.IntegerField(default=True, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=45)),
                ('lname', models.CharField(max_length=45)),
                ('identity', models.IntegerField(default=True)),
                ('mobile', models.IntegerField(default=True)),
                ('address', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='emploeey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.IntegerField(default=100)),
                ('efname', models.CharField(max_length=45)),
                ('elname', models.CharField(max_length=45)),
                ('esalary', models.IntegerField(default=170)),
                ('epassword', models.CharField(max_length=45)),
                ('edateofharing', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='serves',
            fields=[
                ('sname', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('scoast', models.IntegerField(default=100)),
            ],
        ),
        migrations.AddField(
            model_name='custumer',
            name='cserve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.serves'),
        ),
    ]
