# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-04 03:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20190704_0314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custumer',
            name='cserve',
        ),
    ]
