# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-04 04:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20190704_0329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custumer',
            name='cserve',
        ),
        migrations.AddField(
            model_name='custumer',
            name='cserves',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='crm.serves'),
        ),
    ]
