# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-04 04:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20190704_0443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custumer',
            old_name='cserves',
            new_name='cserve',
        ),
    ]
