# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-05 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_auto_20190704_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custumer',
            name='username',
            field=models.CharField(max_length=45, primary_key=True, serialize=False),
        ),
    ]
