# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-05 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_auto_20190705_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custumer',
            name='username',
            field=models.CharField(max_length=45, primary_key=True, serialize=False),
        ),
    ]
